### ISSUE TITLE
go-carbon with carbonserver module enabled can't run on raspberry pi

### ISSUE THREAD

**Issue by azhiltsov** [go-graphite/go-carbon#206]
compiled with 
go version go1.9 linux/amd64
by running
GOOS=linux GOARCH=arm GOARM=5 go build -v github.com/lomik/go-carbon
run as /home/pi/carbon/go-carbon -daemon -config /home/pi/carbon/go-carbon.conf 

while carbonserver enabled
```
[common]
user = "pi"
graph-prefix = "carbon.agents.{host}"
metric-endpoint = "local"
metric-interval = "1m0s"
max-cpu = 2

[whisper]
data-dir = "/mnt/carbon/whisper"
schemas-file = "/home/pi/carbon/storage-schemas.conf"
workers = 4
max-updates-per-second = 10
sparse-create = false
enabled = true

[cache]
max-size = 100000
write-strategy = "noop"

[udp]
listen = ":2003"
enabled = false
log-incomplete = false
buffer-size = 0

[tcp]
listen = ":2003"
enabled = true
buffer-size = 0

[pickle]
listen = ":2004"
max-message-size = 67108864
enabled = false
buffer-size = 0

[carbonlink]
listen = "127.0.0.1:7002"
enabled = false
read-timeout = "30s"

[grpc]
listen = "127.0.0.1:7003"
enabled = false

[carbonserver]
listen = "127.0.0.1:8080"
enabled = true
buckets = 10
metrics-as-counters = false
read-timeout = "60s"
write-timeout = "60s"
query-cache-enabled = false
query-cache-size-mb = 10
find-cache-enabled = false
trigram-index = false
scan-frequency = "5m0s"
max-globs = 100
fail-on-max-globs = false
graphite-web-10-strict-mode = true
internal-stats-dir = ""
stats-percentiles = [99, 98, 95, 75, 50]

[dump]
enabled = false
path = "/var/lib/graphite/dump/"
restore-per-second = 0

[pprof]
listen = "localhost:7007"
enabled = false

[[logging]]
logger = ""
# Log output: filename, "stderr", "stdout", "none", "" (same as "stderr")
file = "stdout"
level = "debug"
encoding = "mixed"
encoding-time = "iso8601"
encoding-duration = "seconds"


``` 
```
pi@pi:~/carbon $ /home/pi/carbon/go-carbon -daemon -config /home/pi/carbon/go-carbon.conf 
[2017-10-13T22:44:36.326+0200] INFO [carbonserver] starting carbonserver {"whisperData": "/mnt/carbon/whisper", "maxGlobs": 100, "scanFrequency": "5m0s"}
[2017-10-13T22:44:36.326+0200] INFO [carbonserver] listening on 127.0.0.1:8080 {}
[2017-10-13T22:44:36.326+0200] INFO [main] started {}
[2017-10-13T22:44:36.425+0200] DEBUG [cache] WriteoutQueue.nextRebuildOnce.Do {"now": "2017-10-13 22:44:36.425522202 +0200 CEST m=+0.213451166", "next": "0001-01-01 00:00:00 +0000 UTC"}
[2017-10-13T22:44:36.426+0200] DEBUG [cache] WriteoutQueue.nextRebuildOnce.Do {"now": "2017-10-13 22:44:36.426640632 +0200 CEST m=+0.214569492", "next": "2017-10-13 22:44:36.526623757 +0200 CEST m=+0.314552565"}
[2017-10-13T22:44:36.426+0200] DEBUG [cache] WriteoutQueue sleep before rebuild {"sleepTime": "99.983073ms"}
----skip
[2017-10-13T22:45:36.099+0200] DEBUG [cache] WriteoutQueue.nextRebuildOnce.Do {"now": "2017-10-13 22:45:36.099538479 +0200 CEST m=+59.887467860", "next": "2017-10-13 22:45:36.199496344 +0200 CEST m=+59.987425569"}
[2017-10-13T22:45:36.099+0200] DEBUG [cache] WriteoutQueue sleep before rebuild {"sleepTime": "99.957709ms"}
[2017-10-13T22:45:36.201+0200] DEBUG [cache] WriteoutQueue.nextRebuildOnce.Do {"now": "2017-10-13 22:45:36.201190219 +0200 CEST m=+59.989119652", "next": "2017-10-13 22:45:36.301146365 +0200 CEST m=+60.089075590"}
[2017-10-13T22:45:36.201+0200] DEBUG [cache] WriteoutQueue sleep before rebuild {"sleepTime": "99.955938ms"}
[2017-10-13T22:45:36.303+0200] DEBUG [cache] WriteoutQueue.nextRebuildOnce.Do {"now": "2017-10-13 22:45:36.303549037 +0200 CEST m=+60.091478470", "next": "2017-10-13 22:45:36.403495913 +0200 CEST m=+60.191425137"}
[2017-10-13T22:45:36.303+0200] DEBUG [cache] WriteoutQueue sleep before rebuild {"sleepTime": "99.946667ms"}
[2017-10-13T22:45:36.327+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.runtime.GOMAXPROCS", "value": 2}
[2017-10-13T22:45:36.327+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.runtime.NumGoroutine", "value": 16}
[2017-10-13T22:45:36.327+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.cache.size", "value": 1}
[2017-10-13T22:45:36.328+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.cache.metrics", "value": 3}
[2017-10-13T22:45:36.328+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.cache.maxSize", "value": 100000}
[2017-10-13T22:45:36.329+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.cache.queries", "value": 0}
[2017-10-13T22:45:36.329+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.cache.overflow", "value": 0}
[2017-10-13T22:45:36.329+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.cache.queueBuildCount", "value": 589}
[2017-10-13T22:45:36.330+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.cache.queueBuildTimeMs", "value": 567}
[2017-10-13T22:45:36.330+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.cache.queueWriteoutTime", "value": 0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11540]

goroutine 33 [running]:
sync/atomic.loadUint64(0x10fd82bc, 0x37ca8, 0x420adc)
	/opt/go/src/sync/atomic/64bit_arm.go:10 +0x3c
github.com/lomik/go-carbon/helper.SendAndSubstractUint64(0x5a3c0f, 0xf, 0x10fd82bc, 0x1116e3e0)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/helper/atomic_utils.go:8 +0x1c
github.com/lomik/go-carbon/carbonserver.(*CarbonserverListener).Stat(0x10fd8200, 0x1116e3e0)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbonserver/carbonserver.go:1574 +0x150
github.com/lomik/go-carbon/carbon.NewCollector.func4.1()
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbon/collector.go:155 +0x5c
github.com/lomik/go-carbon/carbon.(*Collector).collect(0x10fd2e40)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbon/collector.go:205 +0x3c
github.com/lomik/go-carbon/carbon.NewCollector.func6(0x10f16640)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbon/collector.go:195 +0x60
github.com/lomik/go-carbon/helper.(*Stoppable).StartFunc.func1.1(0x10f0ce80, 0x10f16640, 0x10fd2e40)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/helper/stoppable.go:42 +0x24
created by github.com/lomik/go-carbon/helper.(*Stoppable).StartFunc.func1
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/helper/stoppable.go:41 +0x64
```

**Comment by azhiltsov** [comment]
@Civil here the bug report you asked

**Comment by azhiltsov** [comment]
uname -a
Linux pi 4.9.41-v7+ #1023 SMP Tue Aug 8 16:00:15 BST 2017 armv7l GNU/Linux
same issue when compiled with 
 GOOS=linux GOARCH=arm GOARM=7 go build -v github.com/lomik/go-carbon
```
[2017-10-13T23:07:39.550+0200] INFO [stat] collect {"endpoint": "local", "metric": "carbon.agents.pi.cache.queueWriteoutTime", "value": 0}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11540]

goroutine 15 [running]:
sync/atomic.loadUint64(0x11a628bc, 0x378e4, 0x4185bc)
	/opt/go/src/sync/atomic/64bit_arm.go:10 +0x3c
github.com/lomik/go-carbon/helper.SendAndSubstractUint64(0x5938e3, 0xf, 0x11a628bc, 0x11b416a0)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/helper/atomic_utils.go:8 +0x1c
github.com/lomik/go-carbon/carbonserver.(*CarbonserverListener).Stat(0x11a62800, 0x11b416a0)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbonserver/carbonserver.go:1574 +0x150
github.com/lomik/go-carbon/carbon.NewCollector.func4.1()
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbon/collector.go:155 +0x5c
github.com/lomik/go-carbon/carbon.(*Collector).collect(0x11a29320)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbon/collector.go:205 +0x3c
github.com/lomik/go-carbon/carbon.NewCollector.func6(0x11916e00)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbon/collector.go:195 +0x60
github.com/lomik/go-carbon/helper.(*Stoppable).StartFunc.func1.1(0x1190d9a8, 0x11916e00, 0x11a29320)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/helper/stoppable.go:42 +0x24
created by github.com/lomik/go-carbon/helper.(*Stoppable).StartFunc.func1
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/helper/stoppable.go:41 +0x64
```
and  GOOS=linux GOARCH=arm64 GOARM=7 go build -v github.com/lomik/go-carbon
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x4 pc=0x11540]

goroutine 18 [running]:
sync/atomic.loadUint64(0x118d8abc, 0x378e4, 0x4185bc)
	/opt/go/src/sync/atomic/64bit_arm.go:10 +0x3c
github.com/lomik/go-carbon/helper.SendAndSubstractUint64(0x5938e3, 0xf, 0x118d8abc, 0x11a207c0)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/helper/atomic_utils.go:8 +0x1c
github.com/lomik/go-carbon/carbonserver.(*CarbonserverListener).Stat(0x118d8a00, 0x11a207c0)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbonserver/carbonserver.go:1574 +0x150
github.com/lomik/go-carbon/carbon.NewCollector.func4.1()
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbon/collector.go:155 +0x5c
github.com/lomik/go-carbon/carbon.(*Collector).collect(0x118d3ce0)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbon/collector.go:205 +0x3c
github.com/lomik/go-carbon/carbon.NewCollector.func6(0x11816f00)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/carbon/collector.go:195 +0x60
github.com/lomik/go-carbon/helper.(*Stoppable).StartFunc.func1.1(0x1198c250, 0x11816f00, 0x118d3ce0)
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/helper/stoppable.go:42 +0x24
created by github.com/lomik/go-carbon/helper.(*Stoppable).StartFunc.func1
	/home/azhiltsov/go/src/github.com/lomik/go-carbon/helper/stoppable.go:41 +0x64
```
