### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by Quentin-M** [go-graphite/go-carbon#249]
Hi,

Seeing failures on graphite-web when it tries to reach out to the carbonserver for some of the graphs/queries we have:

```
fetch for ['telegraf.procstat.cpu_usage;host=engine-new.production-app.vpn;pidfile=-var-run-redis-redis-server-cache.pid;process_name=redis_session_ratelimit', 'telegraf.procstat.cpu_usage;host=engine-new.production-app.vpn;pidfile=-var-run-redis-redis-server-memoizer.pid;process_name=redis_memoizer', 'telegraf.procstat.cpu_usage;host=engine-new.production-app.vpn;pidfile=-var-run-redis-redis-server.pid;process_name=redis_pubsub_master', 'telegraf.procstat.cpu_usage;host=engine.production-app.vpn;pidfile=-var-run-redis-redis-server-cache.pid;process_name=redis_session_ratelimit', 'telegraf.procstat.cpu_usage;host=engine.production-app.vpn;pidfile=-var-run-redis-redis-server-memoizer.pid;process_name=redis_memoizer', 'telegraf.procstat.cpu_usage;host=engine.production-app.vpn;pidfile=-var-run-redis-redis-server.pid;process_name=redis_pubsub_master']: Error decoding render response from http://graphite-cache-3.graphite-cache.app-production.svc.cluster.local:8080/render/?format=pickle&local=1&noCache=1&from=1536702854&until=1536703154&target=telegraf.procstat.cpu_usage%3Bhost%3Dengine-new.production-app.vpn%3Bpidfile%3D-var-run-redis-redis-server-memoizer.pid%3Bprocess_name%3Dredis_memoizer&target=telegraf.procstat.cpu_usage%3Bhost%3Dengine.production-app.vpn%3Bpidfile%3D-var-run-redis-redis-server-cache.pid%3Bprocess_name%3Dredis_session_ratelimit&target=telegraf.procstat.cpu_usage%3Bhost%3Dengine-new.production-app.vpn%3Bpidfile%3D-var-run-redis-redis-server.pid%3Bprocess_name%3Dredis_pubsub_master&target=telegraf.procstat.cpu_usage%3Bhost%3Dengine.production-app.vpn%3Bpidfile%3D-var-run-redis-redis-server-memoizer.pid%3Bprocess_name%3Dredis_memoizer&target=telegraf.procstat.cpu_usage%3Bhost%3Dengine.production-app.vpn%3Bpidfile%3D-var-run-redis-redis-server.pid%3Bprocess_name%3Dredis_pubsub_master&target=telegraf.procstat.cpu_usage%3Bhost%3Dengine-new.production-app.vpn%3Bpidfile%3D-var-run-redis-redis-server-cache.pid%3Bprocess_name%3Dredis_session_ratelimit&now=1536703154: Ran out of input: Traceback (most recent call last):

  File "/opt/graphite/webapp/graphite/readers/remote.py", line 130, in deserialize
    deserialized = self._deserialize_stream(reader, result.getheader('content-type'))

  File "/opt/graphite/webapp/graphite/readers/remote.py", line 160, in _deserialize_stream
    data = unpickle.load(stream)

  File "/opt/graphite/webapp/graphite/util.py", line 216, in load
    return SafeUnpickler(file).load()

EOFError: Ran out of input
```

The query has quite a few parameters, which leads me to think that go-carbon should support POST alongside GET as a good step forward (right now, switching graphite-web to POST will make go-carbon return `[2018-09-11T22:31:28.358Z] ERROR [access] fetch failed {"handler": "render", "url": "/render/", "peer": "172.16.224.4:58950", "format": "json", "runtime_seconds": 0.00001669, "reason": "invalid 'from' time", "http_code": 400}`). But it may not be the issue. When querying manually, I also see that carbon-server does not return any data at all (`Content-Length: 0`) and that the Content-Type is set to `application/text` rather than `application/pickle`. When switching the format to JSON, the response is also empty.

**Comment by Quentin-M** [comment]
In comparison, when running graphite-web and running the exact same query, I do get an answer, with the right `Content-Type` and `Content-Length: 14` (just a few binary bytes probably meaning there's nothing there).

**Comment by Quentin-M** [comment]
In comparison, when running graphite-web and running the exact same query, I do get an answer, with the right `Content-Type` and `Content-Length: 14`. After unpickling the bytes, the result is `[]`.
