### ISSUE TITLE
Invalid render responses

### ISSUE THREAD

**Issue by devicenull** [go-graphite/go-carbon#262]
I have graphite-web configured with a bunch of gocarbon 0.13.0 backends configured as CLUSTER_SERVERS.  

Whenever I try to render a graph in graphite, I get this error back from it:

<pre>
2018-10-19,15:05:20.697 :: RemoteReader[x.x.x.x:8001] Error decoding render response from http://x.x.x.x:8001/render/?format=pickle&local=1&noCache=1&from=1539889520&until=1539975920&target=health.guests.49.80.63.23360894.cpu.usage&now=1539975920:
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/readers/remote.py", line 130, in deserialize
    deserialized = self._deserialize_stream(reader, result.getheader('content-type'))
  File "/opt/graphite/webapp/graphite/readers/remote.py", line 160, in _deserialize_stream
    data = unpickle.load(stream)
  File "/opt/graphite/webapp/graphite/util.py", line 186, in load
    return pickle_obj.load()
EOFError
</pre>

If I manually wget that URL, I get this:

<pre>
---request begin---
GET /render/?format=pickle&local=1&noCache=1&from=1539889520&until=1539975920&target=health.guests.49.80.63.23360894.cpu.usage&now=1539975920 HTTP/1.1
User-Agent: Wget/1.14 (linux-gnu)
Accept: */*
Host: x.x.x.x:8001
Connection: Keep-Alive

---request end---
HTTP request sent, awaiting response...
---response begin---
HTTP/1.1 200 OK
Content-Type: application/text
Vary: Accept-Encoding
Date: Fri, 19 Oct 2018 19:08:47 GMT
Content-Length: 0

---response end---
</pre>

The way that we've sharded this data means that any given go-carbon instance may not have the required metric, however it seems like go-carbon is not returning what graphite-web expects here.

**Comment by devicenull** [comment]
Somehow I managed to miss the fact that go-graphite/carbonapi exists.  I'm pretty sure we're going to be switching to this, as performance is *significantly* improved (making this entire bug irrelevant)

**Comment by deniszh** [comment]
That's not a bug per se, go-carbon never promised support for graphite clustering protocol. Carbonlink works fine, though.

**Comment by Civil** [comment]
Well, that's a bug but in carbonserver component.

**Comment by Civil** [comment]
Even though it was never advertised that go-carbon supports clustering protocol, as the carbonserver implements necessary bits to support it, it's better for me to fix this bug, but that will be very low-prio for me as it doesn't affect the actual results (or shouldn't affect) as it happens in cases when there is no data available.

**Comment by devicenull** [comment]
> but that will be very low-prio for me as it doesn't affect the actual results (or shouldn't affect) as it happens in cases when there is no data available.

That's not entirely correct.  The only reason I noticed this is because graphite-web was failing to render graphs at all.  The issue was that the metric only lived on one of the cluster servers, and recent versions of graphite-web give up entirely on the first failure from a cluster server.

This may in fact be as graphite-web bug though, in older versions it was much more tolerant to the failure of any given cluster server. Even with these failed requests, graphs still rendered properly in 0.9.16.

**Comment by Civil** [comment]
Yeah, then it's 100% a grpahite-web bug, but I'll check at some point in future if carbonserver should response with something else in case of absent metric.

**Comment by deniszh** [comment]
> Yeah, then it's 100% a grpahite-web bug, but I'll check at some point in future if carbonserver should response with something else in case of absent metric.

Sorry, @Civil, with all respect - but that's only partially graphite-web bug. It expects pickle format, but gets an empty response from go-carbon, which is far from correct behavior.  

@devicenull 
>This may in fact be as graphite-web bug though, in older versions it was much more tolerant to the failure of any given cluster server. Even with these failed requests, graphs still rendered properly in 0.9.16.

Well, that's a consequence of new clustering code in 1.x graphite-web. But if go-carbon reply correctly (with empty pickle array) then it will not consider as error in graphite-web and will continue to work.

**Comment by Civil** [comment]
@deniszh well, I meant that it's at least a graphite-web's bug as it shouldn't stop on such kind of responses.

If it expects for empty set to have a pickled empty array - then it's also a carbonserver's bug which needs to be fixed.

**Comment by biox** [comment]
Bumping this as I'm running into this bug as well. I'll likely have to go ahead and implement carbonzipper + carbonapi to make up for it, though would prefer not to. Either that or I'll write a remote finder for Graphite Web, or would you prefer a PR against this project?

**Comment by deniszh** [comment]
@biox : IMO go-carbon fix is more generic and thus better.

**Comment by biox** [comment]
For those curious, the following graphite-web patch works around go-carbon's 404 responses:

`/opt/graphite/webapp/graphite/finders/remote.py`
```diff
-        if result.status != 200:
+        if result.status == 404:
+            result.data = '[]'
+        elif result.status != 200:
             result.release_conn()
             self.fail()
             log.exception(
                 "RemoteFinder[%s] Error response %d from %s" % (self.host, result.status, url_full))
             raise Exception("Error response %d from %s" % (result.status, url_full))
```

My golang-fu is limited, and I have limited time, but I'll submit a go-carbon patch and attach it to this issue. Before I do, is anyone opposed to 0 metrics returned simply causing carbonserver to return an empty array response, instead of a 404?

**Comment by azhiltsov** [comment]
related to https://github.com/lomik/go-carbon/pull/254

**Comment by jdblack** [comment]
This issue started causing us trouble when we moved  our cache layer to carbonserver. I have created a  PR https://github.com/go-graphite/go-carbon/pull/453  that optionally makes  an empty result  valid.
